# Generated by Django 5.2.15 on 2026-06-07 07:42

from django.db import migrations

def migrate_images(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')
    
    for product in Product.objects.all():
        if product.old_thumbnail:
            ProductImage.objects.create(
                product=product,
                image=product.old_thumbnail,
                is_thumbnail=True
            )
        # We checked earlier that old_images is always empty for existing products.
        # But for completeness:
        for img_url in product.old_images:
            if img_url:
                ProductImage.objects.create(
                    product=product,
                    image=img_url,
                    is_thumbnail=False
                )

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_images_product_old_images_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_images, reverse_code=migrations.RunPython.noop),
    ]
