# Generated by Django 5.2.15 on 2026-06-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20260607_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_thumbnail',
        ),
    ]
