# Generated by Django 6.0.6 on 2026-06-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cooler_height",
            field=models.FloatField(
                blank=True,
                help_text="Height in mm (for Cooler and Case clearance)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="form_factor",
            field=models.CharField(
                blank=True, help_text="ATX, Micro-ATX, etc.", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gaming_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="gpu_length",
            field=models.FloatField(
                blank=True,
                help_text="Length in mm (for GPU and Case clearance)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="m2_slots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="model3d_url",
            field=models.URLField(
                blank=True, help_text="URL to GLTF/GLB model", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pcie_slots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="power_draw",
            field=models.IntegerField(
                default=0, help_text="Power consumption in watts"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="productivity_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="sata_ports",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="socket",
            field=models.CharField(
                blank=True,
                help_text="CPU socket or Motherboard socket support",
                max_length=50,
            ),
        ),
    ]
